### ISSUE TITLE
Construcción de la ventana1 primera parte

### ISSUE THREAD

**Issue by ValentinOsorioM** [ValentinOsorioM/Clase9#1]
Construir la ventana 1 y hacer el formulario para ingresar la información del cliente

**Comment by AlexZapata96** [comment]
saludos,  voy a encargarme  de esta funcionalidad

**Comment by ValentinOsorioM** [comment]
Listo, trabajo cumplido por favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario
