### ISSUE TITLE
Programar el botón para buscar las preguntas de recuperación de contraseña 

### ISSUE THREAD

**Issue by ValentinOsorioM** [ValentinOsorioM/Clase9#7]
Validar que se ingrese el documento del usuario al cual se le va a a buscar la contraseña 
Validar que el documento sea un dato tipo numérico
Crear la clase usuario con sus 11 propiedades 
Solo considerar un password 
Buscar las preguntas para recuperar la contraseña

**Comment by AlexZapata96** [comment]
Enterado, me encargo de este issue.

**Comment by ValentinOsorioM** [comment]
Listo quedo pendiente de su primer push y pull request

**Comment by ValentinOsorioM** [comment]
Se cierra este issue #7
